name: Deploy Calculator Keyboard
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 1.Checkout
        uses: actions/checkout@master

      - name: 2.Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: 3.Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: ^7.6.0
          run_install: false

      - name: 4.Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 5.Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 6.Install dependencies
        run: pnpm install

      - name: 7.Run build task
        run: pnpm run build

      - name: 8.Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avz --delete"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.TARGET }}
            EXCLUDE: "/public/, /node_modules/"
